[tool.black]
line-length = 100
target-version = ["py311","py312"]
exclude = '''
/(
  \.venv
 | \.git
 | \.mypy_cache
 | \.ruff_cache
 | \.pytest_cache
 | build
 | dist
)/
'''


[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [".venv", ".git", ".mypy_cache", ".ruff_cache", ".pytest_cache"]

[tool.ruff.lint]
# moved from [tool.ruff]
select = ["E","F","I","UP","B"]
ignore = ["E501"]  # line length handled by Black

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
strict_optional = true
no_implicit_optional = true
disallow_untyped_defs = true
exclude = "(\\.venv|\\.git|tests/fixtures)"

[tool.pytest.ini_options]
addopts = "-q --strict-markers --disable-warnings"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["chatbot"]

[tool.coverage.report]
show_missing = true
skip_covered = true
